### PR TITLE
Fix Formatting

### PR DESCRIPTION
**Pull request by pcfens**
I'm only fixing the formatting using `terraform fmt` using the latest version of terraform. No functional changes.

### CODE REVIEW

**Review by soroushatarod — APPROVED** [review]
thanks!

**Comment by soroushatarod** [comment]
merge

**Comment by pcfens** [comment]
Thanks for taking a look. Did you mean to approve this but not merge it? I've got a few more changes on the way, but I'm hoping to get this one in first to keep rebasing to a minimum.

**Comment by soroushatarod** [comment]
Sorry, forgot to click the merge button. It's merged now. Thank you

**Pull request merged**
